import '../../features/products/data/models/product_model.dart';

class SampleDataGenerator {
  static List<ProductModel> getSampleProducts() {
    final now = DateTime.now();

    return [
      // Cervezas
      ProductModel(
        name: 'Corona Extra 330ml',
        description: 'Cerveza mexicana premium',
        price: 2.50,
        stock: 48,
        barcode: '7501031300001',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Heineken 330ml',
        description: 'Cerveza holandesa importada',
        price: 2.80,
        stock: 36,
        barcode: '8710103750001',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Modelo Especial 355ml',
        description: 'Cerveza mexicana tradicional',
        price: 2.30,
        stock: 42,
        barcode: '7501031300002',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Budweiser 330ml',
        description: 'Cerveza americana clásica',
        price: 2.20,
        stock: 54,
        barcode: '7501031300003',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Tecate Light 355ml',
        description: 'Cerveza light mexicana',
        price: 2.10,
        stock: 38,
        barcode: '7501031300004',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Dos Equis Lager 355ml',
        description: 'Cerveza mexicana premium',
        price: 2.40,
        stock: 45,
        barcode: '7501031300005',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Pacifico Clara 355ml',
        description: 'Cerveza mexicana clara',
        price: 2.35,
        stock: 40,
        barcode: '7501031300006',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Sol 355ml',
        description: 'Cerveza mexicana clara',
        price: 2.15,
        stock: 52,
        barcode: '7501031300007',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Indio 355ml',
        description: 'Cerveza mexicana oscura',
        price: 2.25,
        stock: 44,
        barcode: '7501031300008',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Victoria 355ml',
        description: 'Cerveza mexicana clásica',
        price: 2.20,
        stock: 46,
        barcode: '7501031300009',
        createdAt: now,
        updatedAt: now,
      ),

      // Helados
      ProductModel(
        name: 'Helado Vainilla 1L',
        description: 'Helado de vainilla cremoso',
        price: 4.50,
        stock: 25,
        barcode: '7501031300010',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Helado Chocolate 1L',
        description: 'Helado de chocolate rico',
        price: 4.50,
        stock: 28,
        barcode: '7501031300011',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Helado Fresa 1L',
        description: 'Helado de fresa natural',
        price: 4.50,
        stock: 22,
        barcode: '7501031300012',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Helado Cookies & Cream 1L',
        description: 'Helado con galletas y crema',
        price: 5.00,
        stock: 20,
        barcode: '7501031300013',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Helado Menta 1L',
        description: 'Helado de menta refrescante',
        price: 4.75,
        stock: 18,
        barcode: '7501031300014',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Helado Pistacho 1L',
        description: 'Helado de pistacho premium',
        price: 5.50,
        stock: 15,
        barcode: '7501031300015',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Helado Caramelo 1L',
        description: 'Helado de caramelo dulce',
        price: 4.75,
        stock: 24,
        barcode: '7501031300016',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Helado Limón 1L',
        description: 'Helado de limón cítrico',
        price: 4.25,
        stock: 16,
        barcode: '7501031300017',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Helado Café 1L',
        description: 'Helado de café con sabor intenso',
        price: 4.75,
        stock: 19,
        barcode: '7501031300018',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Helado Nuez 1L',
        description: 'Helado de nuez premium',
        price: 5.25,
        stock: 14,
        barcode: '7501031300019',
        createdAt: now,
        updatedAt: now,
      ),

      // Galletas
      ProductModel(
        name: 'Galletas Oreo Original 137g',
        description: 'Galletas Oreo clásicas',
        price: 1.80,
        stock: 60,
        barcode: '7501031300020',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Galletas Oreo Chocolate 137g',
        description: 'Galletas Oreo de chocolate',
        price: 1.80,
        stock: 55,
        barcode: '7501031300021',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Galletas Chips Ahoy 300g',
        description: 'Galletas con chispas de chocolate',
        price: 2.50,
        stock: 45,
        barcode: '7501031300022',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Galletas Ritz 200g',
        description: 'Galletas saladas Ritz',
        price: 1.90,
        stock: 50,
        barcode: '7501031300023',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Galletas María 200g',
        description: 'Galletas María tradicionales',
        price: 1.20,
        stock: 70,
        barcode: '7501031300024',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Galletas Animalitos 200g',
        description: 'Galletas de animales divertidas',
        price: 1.50,
        stock: 65,
        barcode: '7501031300025',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Galletas Principe 200g',
        description: 'Galletas Principe con chocolate',
        price: 1.60,
        stock: 58,
        barcode: '7501031300026',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Galletas Digestive 200g',
        description: 'Galletas Digestive integrales',
        price: 1.70,
        stock: 52,
        barcode: '7501031300027',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Galletas Graham 200g',
        description: 'Galletas Graham saludables',
        price: 1.80,
        stock: 48,
        barcode: '7501031300028',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Galletas de Avena 200g',
        description: 'Galletas de avena nutritivas',
        price: 1.90,
        stock: 42,
        barcode: '7501031300029',
        createdAt: now,
        updatedAt: now,
      ),

      // Refrescos
      ProductModel(
        name: 'Coca Cola 600ml',
        description: 'Refresco Coca Cola original',
        price: 1.80,
        stock: 80,
        barcode: '7501031300030',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Coca Cola Zero 600ml',
        description: 'Coca Cola sin azúcar',
        price: 1.80,
        stock: 75,
        barcode: '7501031300031',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Pepsi 600ml',
        description: 'Refresco Pepsi original',
        price: 1.70,
        stock: 72,
        barcode: '7501031300032',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Pepsi Zero 600ml',
        description: 'Pepsi sin azúcar',
        price: 1.70,
        stock: 68,
        barcode: '7501031300033',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Sprite 600ml',
        description: 'Refresco Sprite limón lima',
        price: 1.60,
        stock: 65,
        barcode: '7501031300034',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Fanta Naranja 600ml',
        description: 'Refresco Fanta sabor naranja',
        price: 1.60,
        stock: 58,
        barcode: '7501031300035',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Fanta Uva 600ml',
        description: 'Refresco Fanta sabor uva',
        price: 1.60,
        stock: 52,
        barcode: '7501031300036',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: '7UP 600ml',
        description: 'Refresco 7UP limón lima',
        price: 1.65,
        stock: 55,
        barcode: '7501031300037',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Dr Pepper 600ml',
        description: 'Refresco Dr Pepper original',
        price: 1.90,
        stock: 45,
        barcode: '7501031300038',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Mountain Dew 600ml',
        description: 'Refresco Mountain Dew cítrico',
        price: 1.75,
        stock: 48,
        barcode: '7501031300039',
        createdAt: now,
        updatedAt: now,
      ),

      // Snacks
      ProductModel(
        name: 'Papas Ruffles Original 150g',
        description: 'Papas Ruffles originales',
        price: 2.20,
        stock: 40,
        barcode: '7501031300040',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Papas Ruffles Queso 150g',
        description: 'Papas Ruffles sabor queso',
        price: 2.20,
        stock: 38,
        barcode: '7501031300041',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Papas Sabritas Original 150g',
        description: 'Papas Sabritas originales',
        price: 2.00,
        stock: 45,
        barcode: '7501031300042',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Papas Sabritas Adobadas 150g',
        description: 'Papas Sabritas adobadas',
        price: 2.00,
        stock: 42,
        barcode: '7501031300043',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Doritos Nacho 150g',
        description: 'Doritos sabor nacho',
        price: 2.30,
        stock: 35,
        barcode: '7501031300044',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Doritos Flamin Hot 150g',
        description: 'Doritos Flamin Hot picantes',
        price: 2.30,
        stock: 32,
        barcode: '7501031300045',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Cheetos Flamin Hot 150g',
        description: 'Cheetos Flamin Hot picantes',
        price: 2.10,
        stock: 38,
        barcode: '7501031300046',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Cheetos Puffs 150g',
        description: 'Cheetos Puffs inflados',
        price: 2.10,
        stock: 40,
        barcode: '7501031300047',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Fritos Original 150g',
        description: 'Fritos originales',
        price: 1.90,
        stock: 35,
        barcode: '7501031300048',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Takis Fuego 150g',
        description: 'Takis Fuego extra picantes',
        price: 2.40,
        stock: 28,
        barcode: '7501031300049',
        createdAt: now,
        updatedAt: now,
      ),

      // Dulces
      ProductModel(
        name: 'Chocolate Hershey 43g',
        description: 'Chocolate Hershey clásico',
        price: 1.20,
        stock: 90,
        barcode: '7501031300050',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Chocolate Snickers 57g',
        description: 'Chocolate Snickers con caramelo',
        price: 1.50,
        stock: 85,
        barcode: '7501031300051',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Chocolate Milky Way 58g',
        description: 'Chocolate Milky Way suave',
        price: 1.40,
        stock: 80,
        barcode: '7501031300052',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Chocolate Kit Kat 41g',
        description: 'Chocolate Kit Kat crujiente',
        price: 1.30,
        stock: 88,
        barcode: '7501031300053',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Chocolate M&M Peanut 49g',
        description: 'M&M con cacahuates',
        price: 1.60,
        stock: 75,
        barcode: '7501031300054',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Chocolate M&M Chocolate 47g',
        description: 'M&M de chocolate',
        price: 1.60,
        stock: 78,
        barcode: '7501031300055',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Chocolate Reese 51g',
        description: 'Chocolate Reese con mantequilla',
        price: 1.70,
        stock: 70,
        barcode: '7501031300056',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Chocolate Twix 57g',
        description: 'Chocolate Twix con caramelo',
        price: 1.50,
        stock: 82,
        barcode: '7501031300057',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Chocolate 3 Musketeers 54g',
        description: 'Chocolate 3 Musketeers suave',
        price: 1.40,
        stock: 76,
        barcode: '7501031300058',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Chocolate Butterfinger 60g',
        description: 'Chocolate Butterfinger crujiente',
        price: 1.60,
        stock: 68,
        barcode: '7501031300059',
        createdAt: now,
        updatedAt: now,
      ),

      // Bebidas Energéticas
      ProductModel(
        name: 'Red Bull 250ml',
        description: 'Bebida energética Red Bull',
        price: 3.50,
        stock: 30,
        barcode: '7501031300060',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Monster Energy 473ml',
        description: 'Bebida energética Monster',
        price: 3.20,
        stock: 35,
        barcode: '7501031300061',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Rockstar Energy 473ml',
        description: 'Bebida energética Rockstar',
        price: 3.00,
        stock: 28,
        barcode: '7501031300062',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Powerade Mango 500ml',
        description: 'Bebida deportiva Powerade mango',
        price: 2.20,
        stock: 45,
        barcode: '7501031300063',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Gatorade Limón 500ml',
        description: 'Bebida deportiva Gatorade limón',
        price: 2.20,
        stock: 42,
        barcode: '7501031300064',
        createdAt: now,
        updatedAt: now,
      ),

      // Aguas
      ProductModel(
        name: 'Agua Bonafont 600ml',
        description: 'Agua purificada Bonafont',
        price: 1.20,
        stock: 100,
        barcode: '7501031300065',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Agua Ciel 600ml',
        description: 'Agua purificada Ciel',
        price: 1.10,
        stock: 95,
        barcode: '7501031300066',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Agua Epura 600ml',
        description: 'Agua purificada Epura',
        price: 1.15,
        stock: 88,
        barcode: '7501031300067',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Agua Bonafont 1L',
        description: 'Agua Bonafont 1 litro',
        price: 1.80,
        stock: 75,
        barcode: '7501031300068',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Agua Ciel 1L',
        description: 'Agua Ciel 1 litro',
        price: 1.70,
        stock: 70,
        barcode: '7501031300069',
        createdAt: now,
        updatedAt: now,
      ),

      // Jugos
      ProductModel(
        name: 'Jugo Del Valle Naranja 1L',
        description: 'Jugo Del Valle sabor naranja',
        price: 2.50,
        stock: 40,
        barcode: '7501031300070',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Jugo Del Valle Manzana 1L',
        description: 'Jugo Del Valle sabor manzana',
        price: 2.50,
        stock: 38,
        barcode: '7501031300071',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Jugo Del Valle Uva 1L',
        description: 'Jugo Del Valle sabor uva',
        price: 2.50,
        stock: 35,
        barcode: '7501031300072',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Jugo Jumex Durazno 1L',
        description: 'Jugo Jumex sabor durazno',
        price: 2.30,
        stock: 42,
        barcode: '7501031300073',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Jugo Jumex Mango 1L',
        description: 'Jugo Jumex sabor mango',
        price: 2.30,
        stock: 40,
        barcode: '7501031300074',
        createdAt: now,
        updatedAt: now,
      ),

      // Cervezas Artesanales
      ProductModel(
        name: 'Cerveza Minerva Stout 355ml',
        description: 'Cerveza artesanal Minerva Stout',
        price: 4.50,
        stock: 20,
        barcode: '7501031300075',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Cerveza Minerva IPA 355ml',
        description: 'Cerveza artesanal Minerva IPA',
        price: 4.50,
        stock: 22,
        barcode: '7501031300076',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Cerveza Cucapá Chupacabras 355ml',
        description: 'Cerveza artesanal Cucapá Chupacabras',
        price: 4.80,
        stock: 18,
        barcode: '7501031300077',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Cerveza Cucapá Obscura 355ml',
        description: 'Cerveza artesanal Cucapá Obscura',
        price: 4.80,
        stock: 16,
        barcode: '7501031300078',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Cerveza Calavera Mexican Lager 355ml',
        description: 'Cerveza artesanal Calavera Mexican Lager',
        price: 4.20,
        stock: 25,
        barcode: '7501031300079',
        createdAt: now,
        updatedAt: now,
      ),

      // Helados Especiales
      ProductModel(
        name: 'Helado Ben & Jerry Chocolate Fudge 473ml',
        description: 'Helado premium Ben & Jerry Chocolate Fudge',
        price: 8.50,
        stock: 12,
        barcode: '7501031300080',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Helado Ben & Jerry Cookie Dough 473ml',
        description: 'Helado premium Ben & Jerry Cookie Dough',
        price: 8.50,
        stock: 10,
        barcode: '7501031300081',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Helado Häagen-Dazs Vainilla 473ml',
        description: 'Helado premium Häagen-Dazs vainilla',
        price: 9.00,
        stock: 8,
        barcode: '7501031300082',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Helado Häagen-Dazs Chocolate 473ml',
        description: 'Helado premium Häagen-Dazs chocolate',
        price: 9.00,
        stock: 9,
        barcode: '7501031300083',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Helado Magnum Classic 3pz',
        description: 'Helado Magnum Classic 3 piezas',
        price: 6.50,
        stock: 15,
        barcode: '7501031300084',
        createdAt: now,
        updatedAt: now,
      ),

      // Galletas Premium
      ProductModel(
        name: 'Galletas Oreo Golden 137g',
        description: 'Galletas Oreo Golden premium',
        price: 2.00,
        stock: 35,
        barcode: '7501031300085',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Galletas Oreo Mint 137g',
        description: 'Galletas Oreo Mint con menta',
        price: 2.00,
        stock: 30,
        barcode: '7501031300086',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Galletas Chips Ahoy White Fudge 300g',
        description: 'Galletas Chips Ahoy White Fudge',
        price: 2.80,
        stock: 25,
        barcode: '7501031300087',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Galletas Pepperidge Farm Milano 200g',
        description: 'Galletas premium Pepperidge Farm Milano',
        price: 3.50,
        stock: 20,
        barcode: '7501031300088',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Galletas Pepperidge Farm Chessmen 200g',
        description: 'Galletas premium Pepperidge Farm Chessmen',
        price: 3.20,
        stock: 22,
        barcode: '7501031300089',
        createdAt: now,
        updatedAt: now,
      ),

      // Refrescos Dietéticos
      ProductModel(
        name: 'Coca Cola Diet 600ml',
        description: 'Coca Cola Diet sin azúcar',
        price: 1.80,
        stock: 65,
        barcode: '7501031300090',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Pepsi Diet 600ml',
        description: 'Pepsi Diet sin azúcar',
        price: 1.70,
        stock: 60,
        barcode: '7501031300091',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Sprite Zero 600ml',
        description: 'Sprite Zero sin azúcar',
        price: 1.60,
        stock: 55,
        barcode: '7501031300092',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Fanta Zero Naranja 600ml',
        description: 'Fanta Zero naranja sin azúcar',
        price: 1.60,
        stock: 48,
        barcode: '7501031300093',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: '7UP Zero 600ml',
        description: '7UP Zero sin azúcar',
        price: 1.65,
        stock: 50,
        barcode: '7501031300094',
        createdAt: now,
        updatedAt: now,
      ),

      // Snacks Saludables
      ProductModel(
        name: 'Nueces Mixtas 200g',
        description: 'Mezcla de nueces mixtas',
        price: 4.50,
        stock: 25,
        barcode: '7501031300095',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Almendras 200g',
        description: 'Almendras naturales',
        price: 5.20,
        stock: 20,
        barcode: '7501031300096',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Cacahuates 200g',
        description: 'Cacahuates tostados',
        price: 2.80,
        stock: 35,
        barcode: '7501031300097',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Pistaches 200g',
        description: 'Pistaches premium',
        price: 6.50,
        stock: 15,
        barcode: '7501031300098',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Pasas 200g',
        description: 'Pasas naturales',
        price: 3.20,
        stock: 30,
        barcode: '7501031300099',
        createdAt: now,
        updatedAt: now,
      ),

      // Chicles y Caramelos
      ProductModel(
        name: 'Chicles Trident Menta 14pz',
        description: 'Chicles Trident sabor menta',
        price: 1.50,
        stock: 45,
        barcode: '7501031300100',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Chicles Trident Fresa 14pz',
        description: 'Chicles Trident sabor fresa',
        price: 1.50,
        stock: 42,
        barcode: '7501031300101',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Chicles Orbit Menta 14pz',
        description: 'Chicles Orbit sabor menta',
        price: 1.40,
        stock: 48,
        barcode: '7501031300102',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Caramelos Skittles 61g',
        description: 'Caramelos Skittles multicolor',
        price: 1.80,
        stock: 55,
        barcode: '7501031300103',
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        name: 'Caramelos Starburst 57g',
        description: 'Caramelos Starburst frutales',
        price: 1.70,
        stock: 50,
        barcode: '7501031300104',
        createdAt: now,
        updatedAt: now,
      ),
    ];
  }
}
